version: '3'

services:
  frontend_time:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules # we dont want to rewrite this dir, because in local project we dont have this one 
      - ./frontend:/app  # rewrite frontend files from own-pc to docker-host

  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app 
      
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql # inner docker-host
      #- ./mysql_data:/var/lib/mysql # inner our own pc
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'


volumes:
  mysql_data: